name: build

on:
  push:
    branches: [ main ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-python@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run build script
        run: python3 -u Kattis-Solutions/build.py
